// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDCowDnfAzx9TFqqDwAgDowiMjnXEOb9I',
    appId: '1:604078156830:web:5ce48a60d9e6083006920f',
    messagingSenderId: '604078156830',
    projectId: 'pelisfire-f3c6d',
    authDomain: 'pelisfire-f3c6d.firebaseapp.com',
    storageBucket: 'pelisfire-f3c6d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeKuBka_36TUfir3NwrLkPiL8MNy7yIHw',
    appId: '1:604078156830:android:d3193c06ee6dce6e06920f',
    messagingSenderId: '604078156830',
    projectId: 'pelisfire-f3c6d',
    storageBucket: 'pelisfire-f3c6d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD0OtKSOMTD_x4ETYCEn8D1AjOpehTbpxA',
    appId: '1:604078156830:ios:951634f10b335bb706920f',
    messagingSenderId: '604078156830',
    projectId: 'pelisfire-f3c6d',
    storageBucket: 'pelisfire-f3c6d.appspot.com',
    iosBundleId: 'com.example.pelifire',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD0OtKSOMTD_x4ETYCEn8D1AjOpehTbpxA',
    appId: '1:604078156830:ios:0a91bd82c1b40a4d06920f',
    messagingSenderId: '604078156830',
    projectId: 'pelisfire-f3c6d',
    storageBucket: 'pelisfire-f3c6d.appspot.com',
    iosBundleId: 'com.example.pelifire.RunnerTests',
  );
}
